services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: mercados
      POSTGRES_USER: mercados
      POSTGRES_PASSWORD: mercados

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
